// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ByteCarrot.Datajo.Website.Controllers.Examples
{
    public partial class ExamplesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExamplesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ExamplesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Post()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Post);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExamplesController Actions { get { return MVC.Examples; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Examples";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Examples";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Get = "Get";
            public readonly string Long = "Long";
            public readonly string Post = "Post";
            public readonly string Form = "Form";
            public readonly string JQueryValidation = "JQueryValidation";
            public readonly string UnobtrusiveValidation = "UnobtrusiveValidation";
            public readonly string LoadEvent = "LoadEvent";
            public readonly string ClickEvent = "ClickEvent";
            public readonly string SubmitEvent = "SubmitEvent";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Get = "Get";
            public const string Long = "Long";
            public const string Post = "Post";
            public const string Form = "Form";
            public const string JQueryValidation = "JQueryValidation";
            public const string UnobtrusiveValidation = "UnobtrusiveValidation";
            public const string LoadEvent = "LoadEvent";
            public const string ClickEvent = "ClickEvent";
            public const string SubmitEvent = "SubmitEvent";
        }


        static readonly ActionParamsClass_Post s_params_Post = new ActionParamsClass_Post();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Post PostParams { get { return s_params_Post; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Post
        {
            public readonly string text = "text";
        }
        static readonly ActionParamsClass_Form s_params_Form = new ActionParamsClass_Form();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Form FormParams { get { return s_params_Form; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Form
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_JQueryValidation s_params_JQueryValidation = new ActionParamsClass_JQueryValidation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_JQueryValidation JQueryValidationParams { get { return s_params_JQueryValidation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_JQueryValidation
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_UnobtrusiveValidation s_params_UnobtrusiveValidation = new ActionParamsClass_UnobtrusiveValidation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UnobtrusiveValidation UnobtrusiveValidationParams { get { return s_params_UnobtrusiveValidation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UnobtrusiveValidation
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SubmitEvent s_params_SubmitEvent = new ActionParamsClass_SubmitEvent();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubmitEvent SubmitEventParams { get { return s_params_SubmitEvent; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubmitEvent
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ClickEvent = "ClickEvent";
                public readonly string Form = "Form";
                public readonly string Get = "Get";
                public readonly string JQueryValidation = "JQueryValidation";
                public readonly string JQueryValidationSuccess = "JQueryValidationSuccess";
                public readonly string LoadEvent = "LoadEvent";
                public readonly string Long = "Long";
                public readonly string Post = "Post";
                public readonly string SubmitEvent = "SubmitEvent";
                public readonly string Success = "Success";
                public readonly string UnobtrusiveValidation = "UnobtrusiveValidation";
                public readonly string UnobtrusiveValidationSuccess = "UnobtrusiveValidationSuccess";
            }
            public readonly string ClickEvent = "~/Views/Examples/ClickEvent.cshtml";
            public readonly string Form = "~/Views/Examples/Form.cshtml";
            public readonly string Get = "~/Views/Examples/Get.cshtml";
            public readonly string JQueryValidation = "~/Views/Examples/JQueryValidation.cshtml";
            public readonly string JQueryValidationSuccess = "~/Views/Examples/JQueryValidationSuccess.cshtml";
            public readonly string LoadEvent = "~/Views/Examples/LoadEvent.cshtml";
            public readonly string Long = "~/Views/Examples/Long.cshtml";
            public readonly string Post = "~/Views/Examples/Post.cshtml";
            public readonly string SubmitEvent = "~/Views/Examples/SubmitEvent.cshtml";
            public readonly string Success = "~/Views/Examples/Success.cshtml";
            public readonly string UnobtrusiveValidation = "~/Views/Examples/UnobtrusiveValidation.cshtml";
            public readonly string UnobtrusiveValidationSuccess = "~/Views/Examples/UnobtrusiveValidationSuccess.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ExamplesController : ByteCarrot.Datajo.Website.Controllers.Examples.ExamplesController
    {
        public T4MVC_ExamplesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Get()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Long()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Long);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Post(string text)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Post);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "text", text);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Form()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Form);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Form(ByteCarrot.Datajo.Website.Controllers.Examples.ValidatedFormViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Form);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult JQueryValidation()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JQueryValidation);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult JQueryValidation(ByteCarrot.Datajo.Website.Controllers.Examples.FormViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.JQueryValidation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UnobtrusiveValidation()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnobtrusiveValidation);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UnobtrusiveValidation(ByteCarrot.Datajo.Website.Controllers.Examples.ValidatedFormViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnobtrusiveValidation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LoadEvent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadEvent);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ClickEvent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClickEvent);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SubmitEvent(ByteCarrot.Datajo.Website.Controllers.Examples.ValidatedFormViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitEvent);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SubmitEvent()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SubmitEvent);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
